;Using the new IRI model to calculate the electron temperature values for prelim presentation 
;____________________________________________________________________________________________________________

;Some IRI inputs

idate=2000089;2016205  ;m5 flare
lat=20.  ;m5 flare low sza
lon=105.0



;hour =5. ; m5 flare UT time- local daytime
hour=13 ;nightime
utsec=3600.*hour


;altitude bins
z0=80.
zz=findgen(150)*5.+z0
f107=180.200      ;88.9
f107a=186.681;84.7477
;____________________________________________________________________________________________________________

iyyyy=fix(idate/1000)
doy=-(fix(idate)-(fix(idate/1000)*1000))

localhour=(((utsec/240. + lon)/15. + 24. ) mod 24.) ;PE Model version
;localhour=(utsec/3600. + along/15.)  mod 24.  ;My version NEEDS TO BE CHECKED!!
;localhour=hour+25.                             ;IRI description: LOCAL TIME (OR UNIVERSAL TIME + 25) IN DECIMAL
;________________________________________________________________________________________________________________


;#1 make a file with the inputs to the IRI model

openw, lun_iriinp,'/home/srimoyee/Desktop/nrl_files/sav_files/iri_inputs.dat',/get_lun
printf,lun_iriinp,'alati', 'along', 'iyyyy','mmdd','iut','dhour',$
                  'f107a','f107','height'
printf,lun_iriinp,n_elements(zz)
printf,lun_iriinp,lat
printf,lun_iriinp,lon
printf,lun_iriinp,iyyyy
printf,lun_iriinp,doy
printf,lun_iriinp,localhour
printf,lun_iriinp,f107a
printf,lun_iriinp,f107
printf,lun_iriinp,zz

close, lun_iriinp
;__________________________________________________________________________________________

;#2 make the iri executable file

spawn,$
  "f77 -o iri_idl_interface.exe iri_idl_interface.for irisub.for irifun.for iritec.for iridreg.for igrf.for cira.for iriflip.for"


;__________________________________________________________________________________________

;#3 call the fortran wrapper using spawn command

iri_filename=['/home/srimoyee/Desktop/localpe/iri_idl_interface.exe']  ; fortran executable file/wrapper.
spawn,iri_filename,result

;__________________________________________________________________________________________

;#4 open the output file generated by fortran IRI to get the varibles

iri_outdata=dblarr(2,n_elements(zz))  ;2 columns: eden and etemp

iri_outfile='/home/srimoyee/Desktop/nrl_files/sav_files/iri_outputs_13hUT.dat'
openr, lun_iri, iri_outfile, /get_lun
skip_lun, lun_iri, 1, /lines ; 1 header line
readf, lun_iri , iri_outdata
free_lun, lun_iri

;__________________________________________________________________________________________
;
;#5 save the file data into the local variables


eden=reform(iri_outdata(0,*))
etemp=reform(iri_outdata(1,*))
save,eden,etemp,zz,filename='/home/srimoyee/Desktop/nrl_files/sav_files/iri_15hUT.sav'
;___________________________________________________________________________________________________________________________________________________

end
