loc='C:\Users\srimo\Desktop\nrl_files\sav_files\'

prb_state_file=loc+'new_prob_states_SQ05.sav'
;file has: O_prob_state,O2_prob_state,N2_prob_state
restore, prb_state_file
ionabs_file=loc+'new_crosssec_SQ05.sav'
;file has:spec_wave,sigi_o,sigi_o2,sigi_n2,sigab_o,sigab_o2,sigab_n2
restore, ionabs_file
;___________________________________________________________________________________________________________________________________________________________________
;;PROB    branching ratios for each state, species, and wavelength bin:
;nst=3
;nmaj=3
;lmax=22
;prob=fltarr(nst,nmaj,lmax) ;states species and energies, 0-O, 1-O2, 2- N2
;
;;0-O
;n_cols=(size(O_prob_state))[1]  ;number of states
;
;for l=0,lmax-1 do begin
;  for k=1,n_cols-1 do $
;    prob(k-1,0,l)=O_prob_state(k,l)
;endfor
;
;;1-O2
;n_cols=(size(O2_prob_state))[1]  ;number of states
;
;for l=0,lmax-1 do begin
;  for k=1,n_cols-1 do $
;    prob(k-1,1,l)=O2_prob_state(k,l)
;endfor
;
;
;;2-N2
;n_cols=(size(N2_prob_state))[1]  ;number of states
;
;for l=0,lmax-1 do begin
;  for k=1,n_cols-1 do $
;    prob(k-1,2,l)=N2_prob_state(k,l)
;endfor
;___________________________________________________________________________________________________________________________________________________________________

z0=60.
;zz=findgen(161)*2.+z0

zz=findgen(400)*0.5+z0
jmax=n_elements(zz)
dz=(zz(1:*)-zz(0:-2))
dz=[dz[0],dz]  ;in km

;___________________________________________________________________________________________________________________________________________________________________

idate=20161104
lat=0.
lon=0.
f107=70.
f107a=70.
ap=15

i=6.
hour=float(i)+6.
utsec=3600.*hour
localhour=(((utsec/240. + lon)/15. + 24. ) mod 24.)
;___________________________________________________________________________________________________________________________________________________________________
;  Solomon and Qian 2005
filename='C:\Users\srimo\Desktop\nrl_files\sav_files\Solomon_Qian2005.sav'
;file has:A_fac, fref, wavelength_low, wavelength_high
restore, filename
;___________________________________________________________________________________________________________________________________________________________________

P107 = (F107+F107A)/2.
n_wvl=n_elements(a_fac)
ssflux= fltarr(n_wvl)
for L=0,n_wvl-1 do begin
  SSFLUX(L) = fref(L) * (1. + A_fac(L)*(P107-80.))
  IF (SSFLUX(L) LT 0.8*fref(L)) then SSFLUX(L) = 0.8*fref(L)
endfor

wv1=wavelength_low
wv2=wavelength_high


;___________________________________________________________________________________________________________________________________________________________________


msis=msis2k(zz,idate, utsec,lat,lon,localhour,f107a,f107,ap)
zt=msis.t
zo=msis.o
zo2=msis.o2
zn2=msis.n2

;;-----------------------------------------------------------------------------------------------------------------------------------------
;Srimoyee
;Using the new msis beta to calculate the values
;
;

;;#1 make an file with the inputs to the MSIS model
;openw, lun_msisinp,'C:\Users\Srimo\Desktop\nrl_files\sav_files\msis_inputs.dat',/get_lun
;printf,lun_msisinp,'iyd', 'sec', 'number of altitudes','alt','glat','glong',$
;  'stl','f107a','f107','ap','mass'
;printf,lun_msisinp,idate
;printf,lun_msisinp,utsec
;printf,lun_msisinp,n_elements(zz)
;printf,lun_msisinp,zz
;printf,lun_msisinp,lat
;printf,lun_msisinp,lon
;printf,lun_msisinp,localhour
;printf,lun_msisinp,f107a
;printf,lun_msisinp,f107
;printf,lun_msisinp,ap
;printf,lun_msisinp,1.
;
;close, lun_msisinp
;
;;#2 call the fortran wrapper using spawn command
;
;msis_filename='msis_idl_interface.exe'  ; fortran executable file/wrapper. KEEP The MSIS files in the same directory as localpe
;
;spawn,msis_filename,result,/noshell
;
;;#3 open the output file generated by fortran MSIS to get the varibles
;
;msis_outdata=dblarr(4,n_elements(zz))  ;4 columns: O, O2 and N2 densitiy and temperature
;
;msis_outfile='C:\Users\srimo\Desktop\nrl_files\sav_files\msis_outputs.dat'
;openr, lun_msis, msis_outfile, /get_lun
;skip_lun, lun_msis, 1, /lines ; 2 header lines
;readf, lun_msis , msis_outdata
;free_lun, lun_msis
;
;;#4 save the file data into the local variables
;
;zt=msis_outdata(3,*)
;zo=msis_outdata(0,*)
;zo2=msis_outdata(1,*)
;zn2=msis_outdata(2,*)
;

;___________________________________________________________________________________________________________________________________________________________________

;calculating the vertical column density

zcol_o=fltarr(n_elements(zz))
zcol_o2=fltarr(n_elements(zz))
zcol_n2=fltarr(n_elements(zz))


for i=0, n_elements(zz)-1 do begin
   zcol_o[i]=total(zo[i:-1]*dz[i:-1]*1.e5)
   zcol_o2[i]=total(zo2[i:-1]*dz[i:-1]*1.e5)
   zcol_n2[i]=total(zn2[i:-1]*dz[i:-1]*1.e5)
endfor
;___________________________________________________________________________________________________________________________________________________________________

tau=fltarr(n_elements(zz),n_elements(wv1))
flux=fltarr(n_elements(zz),n_elements(wv1))
photoi_o=fltarr(n_elements(zz))
photoi_o2=fltarr(n_elements(zz))
photoi_n2=fltarr(n_elements(zz))

for i=0, n_elements(zz)-1 do begin
    tau(i,*)=(zcol_o(i)*sigab_o) +(zcol_o2(i)*sigab_o2) + (zcol_n2(i)*sigab_n2); optical depth
    flux(i,*)=ssflux*exp(-1.*tau(i,*))  ; solar flux at each altitude
    photoi_o[i]=total(flux(i,*)*sigi_o*zo(i)*(o_prob_state[1,*]+o_prob_state[2,*]+o_prob_state[3,*]))
    photoi_o2[i]=total(flux(i,*)*sigi_o2*zo2(i)*(o2_prob_state[1,*]+o2_prob_state[2,*]))
    photoi_n2[i]=total(flux(i,*)*sigi_n2*zn2(i)*(n2_prob_state[1,*]+n2_prob_state[2,*]))
endfor

;____________________________________________________________________________________________________________________________________________________________________


plt_loc="C:\Users\Srimo\Desktop\"

;Universal Plot variables

colors=['red','black','dodger blue','purple']
lstyl=[0,2,3,4]
postop=[0.1,0.5,0.45,0.95]
posbot=[0.1,0.1,0.45,0.45]
thck=5.
leg_loc=[0.90, 0.85]
leg_nam=['O ','O!L2!N ','N!L2!N ']

head_tilt='SQ 2005: '

;Photoionisation plot

xr=[10.,10000.]
yr=[min(zz),max(zz)]
xt='Photoionisation (Pi)!C !C(cm!U-3!N s!U-1!N)'
yt='Altitude (km)'
titl=head_tilt+'Photoionization'


w1 = WINDOW(WINDOW_TITLE=head_tilt,DIMENSIONS=[800,800])

pi1=plot(photoi_o,zz,name=leg_nam[0],$
         xtitle=xt,ytitle=yt,title=titl,$
         xstyle=1,ystyle=1,yrange=yr,xrange=xr,xlog=1,$;
         thick=thck,color=colors[0],linestyle=lstyl[0],/current)

pi2=plot(photoi_o2,zz,name=leg_nam[1],$
         thick=thck,color=colors[1],linestyle=lstyl[0],/overplot)

pi3=plot(photoi_n2,zz,name=leg_nam[2],$
         thick=thck,color=colors[2],linestyle=lstyl[0],/overplot)



leg1 = LEGEND(TARGET=[pi1,pi2,pi3], POSITION=leg_loc,/normal)

w1.Save, plt_loc+"photoi_testplot.jpeg", BORDER=10, RESOLUTION=600, /TRANSPARENT

;___________________________________________________________________________________________________________________________________________________________________
;floc="C:\Users\Srimo\Desktop\"
;
;zcol_testfile=floc+'SQ05_test.sav'
;restore, zcol_testfile
;
;
;;xr=[1.,5.e21]
;yr=[min(zz),200.]
;xt='Column Density (cm!U-2!N)'
;yt='Altitude (km)'
;titl=head_tilt
;
;maj=['O ','O!L2!N ','N!L2!N ']
;leg_nam=['Test','IDL glow']
;
;w2 = WINDOW(WINDOW_TITLE=head_tilt,DIMENSIONS=[800,800])
;
;z1=plot(zcol_o,zz,name=leg_nam[0]+maj[0],$
;  xtitle=xt,ytitle=yt,title=titl+maj[0]+'Column Density',$
;;  xstyle=1,ystyle=1,yrange=yr,xrange=xr,xlog=1,$;
;  thick=thck,color=colors[0],linestyle=lstyl[0],/current)
;
;z2=plot(zcol[0,*],zz,name=leg_nam[1]+maj[0],$
;  thick=thck,color=colors[1],linestyle=lstyl[1],/overplot)
;
;leg2 = LEGEND(TARGET=[z1,z2], POSITION=leg_loc,/normal)
;
;;w2.Save, plt_loc+"Ozcol_testplot.jpeg", BORDER=10, RESOLUTION=600, /TRANSPARENT
;
;;______________________________________________________________________________________________
;w3 = WINDOW(WINDOW_TITLE=head_tilt,DIMENSIONS=[800,800])
;
;z3=plot(zcol_o2,zz,name=leg_nam[0]+maj[1],$
;  xtitle=xt,ytitle=yt,title=titl+maj[1]+'Column Density',$
;;   xstyle=1,ystyle=1,yrange=yr,xrange=xr,xlog=1,$;
;  thick=thck,color=colors[0],linestyle=lstyl[0],/current)
;
;z4=plot(zcol[1,*],zz,name=leg_nam[1]+maj[1],$
;  thick=thck,color=colors[1],linestyle=lstyl[1],/overplot)
;
;leg3 = LEGEND(TARGET=[z3,z4], POSITION=leg_loc,/normal)
;
;;w3.Save, plt_loc+"O2zcol_testplot.jpeg", BORDER=10, RESOLUTION=600, /TRANSPARENT
;
;;________________________________________________________________________________________________
;
;w4 = WINDOW(WINDOW_TITLE=head_tilt,DIMENSIONS=[800,800])
;
;z5=plot(zcol_n2,zz,name=leg_nam[0]+maj[2],$
;  xtitle=xt,ytitle=yt,title=titl,$
;;   xstyle=1,ystyle=1,yrange=yr,xrange=xr,xlog=1,$;
;  thick=thck,color=colors[0],linestyle=lstyl[0],/current)
;
;z6=plot(zcol[2,*],zz,name=leg_nam[1]+maj[2],$
;  thick=thck,color=colors[1],linestyle=lstyl[1],/overplot)
;
;leg4 = LEGEND(TARGET=[z5,z6], POSITION=leg_loc,/normal)
;
;;w4.Save, plt_loc+"N2zcol_testplot.jpeg", BORDER=10, RESOLUTION=600, /TRANSPARENT


;___________________________________________________________________________________________________________________________________________________________________

end