C     station.inc

      isr(1)= 'MH' !Millstone Hill
      c_st(1) = 'Millstone Hill ionosonde'
      xlat(1) =  42.60
C      xlon(1) = 288.5
      xlon(1) = -71.5

      isr(2)= 'CT' !Chilton
      c_st(2) = 'Chilton ionosonde'
      xlat(2) =  51.5
C      xlon(2) =  359.4
      xlon(2) =  -0.6

      isr(3)= 'WK' !Wakkanai
      c_st(3) = 'Wakkanai ionosonde'
      xlat(3) =  45.16
      xlon(3) =  141.75
