C     station.inc

      isr(1)= 'MH' !Millstone Hill
      c_st(1) = 'Millstone Hill ionosonde'
      xlat(1) =  42.60
      xlon(1) = -71.5  !  288.5

      isr(2)= 'BD' !Boulder
      c_st(2) = 'Boulder ionosonde'
      xlat(2) =  40.00
      xlon(2) =  -105.3 ! 254.7

      isr(3)= 'JM' !Jicamarca
      c_st(3) = 'Jicamarca ionosonde'
      xlat(3) =  -12.0
      xlon(3) =  -76.8 ! 283.2

      isr(4)= 'EL' !Eglin AFB
      c_st(4) = 'Eglin AFB ionosonde'
      xlat(4) =  30.50
      xlon(4) =  -86.5 ! 273.5

      isr(5)= 'IN' !Idaho National Lab
      c_st(5) = 'Idaho National Lab ionosonde'
      xlat(5) =  43.81
      xlon(5) =  -112.7 ! 247.32

      isr(6)= 'CT' !Chilton
      c_st(6) = 'Chilton ionosonde'
      xlat(6) =  51.5
      xlon(6) =  -0.6 ! 359.40

      isr(7)= 'PH' !Pruhonice
      c_st(7) = 'Pruhonice ionosonde'
      xlat(7) =  50.0
      xlon(7) =  14.60 !

      isr(8)= 'ER' !Ebre
      c_st(8) = 'Ebre ionosonde'
      xlat(8) =  40.80
      xlon(8) =  0.50

      isr(9)= 'AT' !Athen
      c_st(9) = 'Athen ionosonde'
      xlat(9) =  38.00
      xlon(9) =  23.5

      isr(10)= 'PS' !Port Stanley ionosonde
      c_st(10) = 'Port Stanley ionosonde'
      xlat(10) =  -51.6
      xlon(10) =  -57.9 ! 302.1

      isr(11)= 'RM' !Ramey ionosonde
      c_st(11) = 'Ramey ionosonde'
      xlat(11) = 18.5
      xlon(11) = 292.9

      isr(12)= 'GS' !'Grahamstown ionosonde'
      c_st(12) = 'Grahamstown ionosonde'
      xlat(12) = -33.3
      xlon(12) =  26.5

      isr(13)= 'HM' ! 'Hermanus ionosonde'
      c_st(13) = 'Hermanus ionosonde'
      xlat(13) =  -34.4
      xlon(13) = 19.2

      isr(14)= 'LV' ! 'Louisvale ionosonde'
      c_st(14) = 'Louisvale ionosonde'
      xlat(14) = -28.5
      xlon(14) =  21.2
